version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ci
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: build
    groups:
      bun-minor-and-patch:
        update-types: [minor, patch]

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: build
    groups:
      go-minor-and-patch:
        update-types: [minor, patch]
